services:
  
  mysql:
    image: mariadb:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./docker/mysql/.env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal
        
  drupal:
    build: docker/phpfpm
    container_name: drupal
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - internal
      - external
    volumes:
      - ./app:/var/www/html
  
  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/certbot:/etc/letsencrypt
    networks:
      - external
  
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker/certbot:/etc/letsencrypt
      - ./app:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html/web --email sammy@your_domain --agree-tos --no-eff-email --staging -d your_domain -d www.your_domain

networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  db-data:
  certbot-etc:
